name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: integration-test
    env:
      CBP_KEY: secrets.GBP_KEY
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: tell me a secret
      run: echo "KEY: $CBP_KEY"

          #- name: Make Docker Containers
          #  run: make containers

          #- name: Run Test
          #  run: make ctests
